# Generated by Django 4.1.2 on 2022-10-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_place_role_user_place_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_place', to='api_user.place'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='api_user.place'),
        ),
        migrations.AlterModelTable(
            name='place',
            table='Place',
        ),
    ]
