# Generated by Django 4.1.2 on 2022-10-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_place_no_alter_user_place_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='api_user.role'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
